### ISSUE TITLE
Week 10 Oct - 16 Oct

### ISSUE THREAD

**Issue by octref** [octref/vscode#5]
### Icon

Currently icon theme determines which icon to use based on file extension, file name, isExpandable etc. This wouldn't apply well to custom tree.
One way to do it is to allow:
```
    "explorer": {
      "treeExplorerNodeProviderId": "pineTree",
      "treeLabel": "Pine Tree!!",
      "icon": "media/pineTree.svg",
      "nodeIcons": {
        "typeA": "media/a.svg",
        "typeB": "media/b.svg"
      }
    }
```

Each node will have a `type` where they can specify `typeA` or `typeB`.
This allows us to create css classes when loading the extension. Can check all icons are valid upon loading. And the API will look more consistent to current file icons.

Another option is to allow an `icon` prop for each node.

### Ordering of Activity Bar icons

I think ultimately this should be configurable through user setting.
Better to leave out for next iteration when we get some feedback from user. Now we can just rank them alphabetically.

### Enabling/Disabling

I think we can wait for Disabling extension to land in October and use it. Also extension author could specify activation event.

### Making treeProvider generic & adding getLabel, getShouldInitiallyExpand, etc

There is no generic on any other API. I feel a bit uneasy about introducing it.

This works well enough for now, I think:

```ts
class OutlineNodeProvider implements TreeExplorerNodeProvider {

  provideRootNode(): Thenable<OutlineNode> {
  }

  resolveChildren(node: OutlineNode): Thenable<OutlineNode[]> {
  }
}

class OutlineNode implements TreeExplorerNode {
}

```

The interface looks like this:

```ts
export interface TreeExplorerNodeProvider {
	provideRootNode(): Thenable<TreeExplorerNode>;
	resolveChildren(node: TreeExplorerNode): Thenable<TreeExplorerNode[]>;
}

export interface TreeExplorerNode {
	label: string;
	shouldInitiallyExpand: boolean;
	onClickCommand: string;
}
```

**Comment by octref** [comment]
## Todo:

- [ ] Add icon for each node
- [ ] Make Provider generic
- [ ] Create another provider that extract information required for rendering like `getLabel(node: any)`
- [ ] Add cancellation token to API
- [ ] Error handling for commands
- [ ] Error handling for resolveChildren
- [ ] Add test

**Comment by octref** [comment]
## Need discussion

- Add icon for each node -- Do we allow remotely loaded icons?

**Comment by octref** [comment]
- [ ] Hide/Toggle command
- [ ] API Doc
- [ ] show/hide -> put config in localStorage
- [ ] Show/hide depending on config in localStorage on launch
